apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: container-info
  spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    type: NodePort
    selector:
      app: container-info
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: container-info
    labels:
      app: container-info
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: container-info
    template:
      metadata:
        labels:
          app: container-info
      spec:
        containers:
          - name: container-info
            image: gluobe/container-info:green
