kind: PersistentVolume
apiVersion: v1
metadata:
  name: lab-09-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data/images"
